CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

OBJS =	gen_fixedlengthcode.o \
		patchedframeofreference.o \
		indexcompression.o
		

LIBS =

TARGET =	indexcompression

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

	
all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
